export const woudbinefcts = [
  'Canada has over 2 million lakes, the largest number in the world.',
  'Niagara Falls can freeze over in winter, forming walls of ice.',
  'Banff National Park in Alberta is Canada’s first national park (1885).',
  'Lake Louise in Alberta is emerald green due to the minerals crushed by glaciers.',
  'Yoho Park (British Columbia) has the “Natural Bridge” rock, created by water carving its way through the rock.',
  'On Vancouver Island, giant Douglas fir trees grow, reaching over 75 meters in height.',
  'The Bay of Fundy between Nova Scotia and New Brunswick has the highest tides in the world, reaching up to 16 meters.',
  'On Prince Edward Island, the soil is bright red due to its high iron content.',
  'In Jasper Park, you can see one of the darkest night skies in the world - ideal for stargazing.',
  'In northern Canada, there is the so-called “Forest Tundra” - an area where forests and tundra literally intertwine.',
  'Montreal is considered the “city of festivals”, hosting more than 100 major events every year.',
  'In Quebec, the old quarter of Vieux-Québec has been preserved, reminiscent of medieval France.',
  'Toronto has the tallest television tower in North America - the CN Tower (553 meters).',
  'Calgary is famous for its “Stampede” - a cowboy festival that attracts more than a million guests.',
  'The city of Whitehorse (Yukon) has more dogs per capita than any other city in Canada.',
  'In the capital, Ottawa, the Rideau Canal turns into the world’s longest natural skating rink in winter - 7.8 km.',
  'Vancouver is considered one of the best cities in the world to live in terms of environmental quality.',
  'Winnipeg is home to the Human Rights Museum, the only one in the world with such a theme.',
  'In Saskatchewan, you can see roads that “disappear” into the horizon – the province is so flat that you can see for tens of kilometers.',
  'In Victoria (British Columbia), more than 3,000 species of flowers grow in the famous Butchart Gardens.',
  'The maple leaf became the national symbol of Canada in the 19th century, long before the flag.',
  'Canada has two official anthems – English and French.',
  'The official languages ​​of Canada are English and French, but more than 200 different ones are spoken in the country.',
  'The main dish of Quebec is poutine: French fries with cheese and sauce.',
  'Canada created the legendary game of hockey, but lacrosse is also officially recognized as a national sport.',
  'In Newfoundland, the traditions of Irish songs and dances are still alive today - they were brought here by settlers.',
  'Manitoba hosts an annual Winter Snow Sculpture Festival.',
  'Canada is the largest producer of maple syrup in the world: about 70% comes from Quebec.',
  'In Windsor (Ontario) grows the largest collection of Japanese sakura in Canada.',
  'In the city of Churchill (Manitoba) you can find the largest number of polar bears in the wild - they are even called the “capital of polar bears”.',
];
